def nft_nat4_rules():
    return {'nftables': [{'metainfo': {'version': '1.0.6',
                                       'release_name': 'Lester Gooch #5',
                                       'json_schema_version': 1}},
                         {'table': {'family': 'inet', 'name': '_netcrave', 'handle': 11}},
                         {'map': {'family': 'inet',
                                  'name': 'masquerade_networks4',
                                  'table': '_netcrave',
                                  'type': ['iface_index', 'ipv4_addr'],
                                  'handle': 3,
                                  'map': 'verdict',
                                  'flags': ['interval']}},
                         {'chain': {'family': 'inet',
                                    'table': '_netcrave',
                                    'name': 'nat_chain',
                                    'handle': 1,
                                    'type': 'filter',
                                    'hook': 'postrouting',
                                    'prio': 0,
                                    'policy': 'accept'}},
                         {'chain': {'family': 'inet',
                                    'table': '_netcrave',
                                    'name': 'masq',
                                    'handle': 2}},
                         {'rule': {'family': 'inet',
                                   'table': '_netcrave',
                                   'chain': 'masq',
                                   'handle': 4,
                                   'expr': [{'masquerade': None}]}}]}
