def nft_nat4_rules():
    return {'nftables': [{'metainfo': {'version': '1.0.6',
                                       'release_name': 'Lester Gooch #5',
                                       'json_schema_version': 1}},
                         {'table': {'family': 'inet', 'name': '_netcrave', 'handle': 22}},
                         {'map': {'family': 'inet',
                                  'name': 'masquerade_networks4',
                                  'table': '_netcrave',
                                  'type': ['iface_index', 'ipv4_addr'],
                                  'handle': 3,
                                  'map': 'verdict',
                                  'flags': ['interval']}},
                         {'chain': {'family': 'inet',
                                    'table': '_netcrave',
                                    'name': 'nat_chain',
                                    'handle': 1,
                                    'type': 'nat',
                                    'hook': 'postrouting',
                                    'prio': 100,
                                    'policy': 'accept'}},
                         {'chain': {'family': 'inet',
                                    'table': '_netcrave',
                                    'name': 'masq',
                                    'handle': 2}},
                         {'rule': {'family': 'inet',
                                   'table': '_netcrave',
                                   'chain': 'nat_chain',
                                   'handle': 4,
                                   'expr': [{'vmap': {'key': {'concat': [{'meta': {'key': 'oif'}},
                                                                         {'payload': {'protocol': 'ip', 'field': 'saddr'}}]},
                                                      'data': '@masquerade_networks4'}}]}},
                         {'rule': {'family': 'inet',
                                   'table': '_netcrave',
                                   'chain': 'masq',
                                   'handle': 5,
                                   'expr': [{'masquerade': None}]}}]}
