def get_netcrave_containerd_config():
    return {'disabled_plugins': [],
            'imports': ['/etc/netcrave/_netcrave.containerd.toml'],
            'oom_score': 0,
            'plugin_dir': '',
            'required_plugins': [],
            'root': '/srv/netcrave/_netcrave/containerd',
            'state': '/run/netcrave/_netcrave/containerd',
            'temp': '',
            'version': 2,
            'cgroup': {'path': ''},
            'debug': {'address': '', 'format': '', 'gid': 0, 'level': '', 'uid': 0},
            'grpc': {'address': '/run/containerd/containerd.sock',
                     'gid': 0,
                     'max_recv_message_size': 16777216,
                     'max_send_message_size': 16777216,
                     'tcp_address': '',
                     'tcp_tls_ca': '',
                     'tcp_tls_cert': '',
                     'tcp_tls_key': '',
                     'uid': 0},
            'metrics': {'address': '', 'grpc_histogram': False},
            'plugins': {'io.containerd.gc.v1.scheduler': {'deletion_threshold': 0,
                                                          'mutation_threshold': 100,
                                                          'pause_threshold': 0.02,
                                                          'schedule_delay': '0s',
                                                          'startup_delay': '100ms'},
                        'io.containerd.grpc.v1.cri': {'cdi_spec_dirs': ['/etc/cdi', '/var/run/cdi'],
                                                      'device_ownership_from_security_context': False,
                                                      'disable_apparmor': False,
                                                      'disable_cgroup': False,
                                                      'disable_hugetlb_controller': True,
                                                      'disable_proc_mount': False,
                                                      'disable_tcp_service': True,
                                                      'drain_exec_sync_io_timeout': '0s',
                                                      'enable_cdi': False,
                                                      'enable_selinux': False,
                                                      'enable_tls_streaming': False,
                                                      'enable_unprivileged_icmp': False,
                                                      'enable_unprivileged_ports': False,
                                                      'ignore_image_defined_volumes': False,
                                                      'image_pull_progress_timeout': '5m0s',
                                                      'max_concurrent_downloads': 3,
                                                      'max_container_log_line_size': 16384,
                                                      'netns_mounts_under_state_dir': False,
                                                      'restrict_oom_score_adj': False,
                                                      'sandbox_image': 'registry.k8s.io/pause:3.8',
                                                      'selinux_category_range': 1024,
                                                      'stats_collect_period': 10,
                                                      'stream_idle_timeout': '4h0m0s',
                                                      'stream_server_address': '127.0.0.1',
                                                      'stream_server_port': '0',
                                                      'systemd_cgroup': False,
                                                      'tolerate_missing_hugetlb_controller': True,
                                                      'unset_seccomp_profile': '',
                                                      'cni': {'bin_dir': '/usr/lib/cni',
                                                              'conf_dir': '/etc/cni/net.d',
                                                              'conf_template': '',
                                                              'ip_pref': '',
                                                              'max_conf_num': 1,
                                                              'setup_serially': False},
                                                      'containerd': {'default_runtime_name': 'runc',
                                                                     'disable_snapshot_annotations': True,
                                                                     'discard_unpacked_layers': False,
                                                                     'ignore_blockio_not_enabled_errors': False,
                                                                     'ignore_rdt_not_enabled_errors': False,
                                                                     'no_pivot': False,
                                                                     'snapshotter': 'overlayfs',
                                                                     'default_runtime': {'base_runtime_spec': '',
                                                                                         'cni_conf_dir': '',
                                                                                         'cni_max_conf_num': 0,
                                                                                         'container_annotations': [],
                                                                                         'pod_annotations': [],
                                                                                         'privileged_without_host_devices': False,
                                                                                         'privileged_without_host_devices_all_devices_allowed': False,
                                                                                         'runtime_engine': '',
                                                                                         'runtime_path': '',
                                                                                         'runtime_root': '',
                                                                                         'runtime_type': '',
                                                                                         'sandbox_mode': '',
                                                                                         'snapshotter': '',
                                                                                         'options': {}},
                                                                     'runtimes': {'runc': {'base_runtime_spec': '',
                                                                                           'cni_conf_dir': '',
                                                                                           'cni_max_conf_num': 0,
                                                                                           'container_annotations': [],
                                                                                           'pod_annotations': [],
                                                                                           'privileged_without_host_devices': False,
                                                                                           'privileged_without_host_devices_all_devices_allowed': False,
                                                                                           'runtime_engine': '',
                                                                                           'runtime_path': '',
                                                                                           'runtime_root': '',
                                                                                           'runtime_type': 'io.containerd.runc.v2',
                                                                                           'sandbox_mode': 'podsandbox',
                                                                                           'snapshotter': '',
                                                                                           'options': {'BinaryName': '',
                                                                                                       'CriuImagePath': '',
                                                                                                       'CriuPath': '',
                                                                                                       'CriuWorkPath': '',
                                                                                                       'IoGid': 0,
                                                                                                       'IoUid': 0,
                                                                                                       'NoNewKeyring': False,
                                                                                                       'NoPivotRoot': False,
                                                                                                       'Root': '',
                                                                                                       'ShimCgroup': '',
                                                                                                       'SystemdCgroup': False}}},
                                                                     'untrusted_workload_runtime': {'base_runtime_spec': '',
                                                                                                    'cni_conf_dir': '',
                                                                                                    'cni_max_conf_num': 0,
                                                                                                    'container_annotations': [],
                                                                                                    'pod_annotations': [],
                                                                                                    'privileged_without_host_devices': False,
                                                                                                    'privileged_without_host_devices_all_devices_allowed': False,
                                                                                                    'runtime_engine': '',
                                                                                                    'runtime_path': '',
                                                                                                    'runtime_root': '',
                                                                                                    'runtime_type': '',
                                                                                                    'sandbox_mode': '',
                                                                                                    'snapshotter': '',
                                                                                                    'options': {}}},
                                                      'image_decryption': {'key_model': 'node'},
                                                      'registry': {'config_path': '',
                                                                   'auths': {},
                                                                   'configs': {},
                                                                   'headers': {},
                                                                   'mirrors': {}},
                                                      'x509_key_pair_streaming': {'tls_cert_file': '', 'tls_key_file': ''}},
                        'io.containerd.internal.v1.opt': {'path': '/var/lib/containerd/opt'},
                        'io.containerd.internal.v1.restart': {'interval': '10s'},
                        'io.containerd.internal.v1.tracing': {'sampling_ratio': 1.0,
                                                              'service_name': 'containerd'},
                        'io.containerd.metadata.v1.bolt': {'content_sharing_policy': 'shared'},
                        'io.containerd.monitor.v1.cgroups': {'no_prometheus': False},
                        'io.containerd.nri.v1.nri': {'disable': True,
                                                     'disable_connections': False,
                                                     'plugin_config_path': '/etc/nri/conf.d',
                                                     'plugin_path': '/opt/nri/plugins',
                                                     'plugin_registration_timeout': '5s',
                                                     'plugin_request_timeout': '2s',
                                                     'socket_path': '/var/run/nri/nri.sock'},
                        'io.containerd.runtime.v1.linux': {'no_shim': False,
                                                           'runtime': 'runc',
                                                           'runtime_root': '',
                                                           'shim': 'containerd-shim',
                                                           'shim_debug': False},
                        'io.containerd.runtime.v2.task': {'platforms': ['linux/amd64'],
                                                          'sched_core': False},
                        'io.containerd.service.v1.diff-service': {'default': ['walking']},
                        'io.containerd.service.v1.tasks-service': {'blockio_config_file': '',
                                                                   'rdt_config_file': ''},
                        'io.containerd.snapshotter.v1.aufs': {'root_path': ''},
                        'io.containerd.snapshotter.v1.blockfile': {'fs_type': '',
                                                                   'mount_options': [],
                                                                   'root_path': '',
                                                                   'scratch_file': ''},
                        'io.containerd.snapshotter.v1.btrfs': {'root_path': ''},
                        'io.containerd.snapshotter.v1.devmapper': {'async_remove': False,
                                                                   'base_image_size': '',
                                                                   'discard_blocks': False,
                                                                   'fs_options': '',
                                                                   'fs_type': '',
                                                                   'pool_name': '',
                                                                   'root_path': ''},
                        'io.containerd.snapshotter.v1.native': {'root_path': ''},
                        'io.containerd.snapshotter.v1.overlayfs': {'mount_options': [],
                                                                   'root_path': '',
                                                                   'sync_remove': False,
                                                                   'upperdir_label': False},
                        'io.containerd.snapshotter.v1.zfs': {'root_path': ''},
                        'io.containerd.tracing.processor.v1.otlp': {'endpoint': '',
                                                                    'insecure': False,
                                                                    'protocol': ''},
                        'io.containerd.transfer.v1.local': {'config_path': '',
                                                            'max_concurrent_downloads': 3,
                                                            'max_concurrent_uploaded_layers': 3,
                                                            'unpack_config': [{'differ': '',
                                                                               'platform': 'linux/amd64',
                                                                               'snapshotter': 'overlayfs'}]}},
            'proxy_plugins': {},
            'stream_processors': {'io.containerd.ocicrypt.decoder.v1.tar': {'accepts': ['application/vnd.oci.image.layer.v1.tar+encrypted'],
                                                                            'args': ['--decryption-keys-path', '/etc/containerd/ocicrypt/keys'],
                                                                            'env': ['OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf'],
                                                                            'path': 'ctd-decoder',
                                                                            'returns': 'application/vnd.oci.image.layer.v1.tar'},
                                  'io.containerd.ocicrypt.decoder.v1.tar.gzip': {'accepts': ['application/vnd.oci.image.layer.v1.tar+gzip+encrypted'],
                                                                                 'args': ['--decryption-keys-path', '/etc/containerd/ocicrypt/keys'],
                                                                                 'env': ['OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf'],
                                                                                 'path': 'ctd-decoder',
                                                                                 'returns': 'application/vnd.oci.image.layer.v1.tar+gzip'}},
            'timeouts': {'io.containerd.timeout.bolt.open': '0s',
                         'io.containerd.timeout.metrics.shimstats': '2s',
                         'io.containerd.timeout.shim.cleanup': '5s',
                         'io.containerd.timeout.shim.load': '5s',
                         'io.containerd.timeout.shim.shutdown': '3s',
                         'io.containerd.timeout.task.state': '2s'},
            'ttrpc': {'address': '', 'gid': 0, 'uid': 0}}
